### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by faisalhabibgit** [SOEN341-Group1/KoalaCal#29]
<img width="726" alt="screen shot 2017-01-27 at 5 29 47 pm" src="https://cloud.githubusercontent.com/assets/24264046/22389946/537bd442-e4b6-11e6-9e34-409ca8a80d3c.png">

Source : https://www.usertesting.com/blog/2015/11/05/why-you-should-user-test-your-prototype-before-coding-anything/

Again if you guys don't wanna waste too much time on making a Prototype we can always just make sketches on pages just to understand the flow of our whole program before we start implementing. if It would have been a huge project I would have said making a prototype is necessary.

**Comment by RemusCM** [comment]
Since we now know the subject of the project, I think we should definitely look into meeting up and sketching the project onto paper. I think we all have different ideas for the project, and it would help a lot for us to write/sketch them all down. This way, we are all on the same page, and the project becomes clearer for everyone. Afterwards, we could maybe do a prototype if time allows it in order to be 100% clear on what is to be done.

**Comment by NepheriusIsTaken** [comment]
Sure. How about we all sketch something separately on a piece of paper and compare everyone's ideas Wednesday after class?
