### ISSUE TITLE
Coding the calendar interface

### ISSUE THREAD

**Issue by NepheriusIsTaken** [SOEN341-Group1/KoalaCal#75]

**Comment by jaslatendresse** [comment]
That would be what the user sees when they are logged in. The message logo would be for the admin when they received requests. Adding events by double clicking a day. Adding event type in the legend below. Possibility to check/uncheck event types you want to display on the calendar. Can change week view to day view to month view. 

This is a first try. I tried to go towards the minimalistic design as that's what I like to use...colors were chosen randomly and of course can be changed. 

Event happening at the same time could be display vertically or horizontally. 

![screen shot 2017-02-05 at 12 14 26 pm](https://cloud.githubusercontent.com/assets/17911957/22628134/c055246e-eb9c-11e6-9bb4-4692847c9189.png)

**Comment by g-harel** [comment]
I've attached some screenshots of what I made with Adobe XD.

Still need to make the add/detail/edit event interface, but I thought I could see what you guys think of what I have so far.

We will also need to decide how to treat overlapping events.

![login](https://cloud.githubusercontent.com/assets/9319710/22632063/164b9e4c-ebe4-11e6-8cb5-f717467161f4.png)
![week](https://cloud.githubusercontent.com/assets/9319710/22632062/1649fdb2-ebe4-11e6-8f46-d15f528a782e.png)
![dropdown](https://cloud.githubusercontent.com/assets/9319710/22632060/16490920-ebe4-11e6-9566-19df131aa0ba.png)
![month](https://cloud.githubusercontent.com/assets/9319710/22632061/164983b4-ebe4-11e6-989c-aab4bb147fc7.png)

**Comment by jaslatendresse** [comment]
@g-harel nice. Just not sure but the nav bar is horizontal on top?

**Comment by g-harel** [comment]
@jaslatendresse What do you mean by navbar?

**Comment by jaslatendresse** [comment]
@g-harel where you see different calendars where you can add events and such

**Comment by g-harel** [comment]
The dropdown allows you to do that. You can toggle calendars by clicking on the colored name, or add events to it with the button in the same row.

**Comment by jaslatendresse** [comment]
Edit to my first post. Added some functionalities. 

![koalacal1](https://cloud.githubusercontent.com/assets/17911957/22658077/d29c9b5a-ec66-11e6-9c18-d3e1153fcfe5.png)
![koalacal2](https://cloud.githubusercontent.com/assets/17911957/22658078/d29ccb34-ec66-11e6-8491-bddd04935561.png)

**Comment by NepheriusIsTaken** [comment]
You'll find attached my shitty hand drawing of the calendar. We'll start the discussion about different options tomorrow.

[Doc Feb 06, 2017, 18_40.pdf](https://github.com/SOEN341-Group1/KoalaCal/files/756153/Doc.Feb.06.2017.18_40.pdf)

**Comment by RemusCM** [comment]
![Navigation bar](https://cloud.githubusercontent.com/assets/14827583/22672186/4f187990-eca0-11e6-9d73-4c7332efad4b.png)

![List of Schedules page](https://cloud.githubusercontent.com/assets/14827583/22672195/596db04a-eca0-11e6-8750-87230b2a03d2.PNG)

![Adding new Schedule](https://cloud.githubusercontent.com/assets/14827583/22672208/679beee8-eca0-11e6-952c-bdf61a6c17dc.PNG)

![Choosing a schedule from the list](https://cloud.githubusercontent.com/assets/14827583/22672219/74a70ffa-eca0-11e6-9595-26410cd69b6c.PNG)

For the last image, I also added in what would happen if you would want to add a new element (you'd need first to choose a month, unless you want to add it to the list.)Adding a new element to a private schedule such as a link the professor gave (i.e. not your own schedule), makes a new schedule with its own link to consider your own.

I like both designs of the log-in page, along with Jasmine's weekly schedule design, so I didn't bother designing those.

**Comment by faisalhabibgit** [comment]
Great work guys! Incredible 
I will also come up with one. Since I have two midterms this week but still going to try to come up with one

**Comment by jaslatendresse** [comment]
Good work everyone

**Comment by g-harel** [comment]
I'll get the ball rolling with some feedback.

Please tell me if I didn't understand a certain element, I am aware that the designs are just prototypes and that I might be missing details.

Jasmine
- I feel like there is a lot of information/ui elements in your calendar view that do not need to be there all the time. We want as much of the screen to be given to the calendar and the big menus take up a lot of the screen.
- The pending requests in a horizontal line would introduce sideways scroll (which is a bit awkward) and can cut off paragraphs awkwardly because of the thinness oh the items.
- I like the calendar menu, but what are the horizontal lines for ?

Remus
- Similar to with Jasmine, I think that the menus/logo are taking away valuable screen space from the calendar.
- I know this is an ongoing discussion, but I'm really not a fan of the tabbed layout. We are building something much more like a web application than a blog/traditional website, I don't really see the need for the extra screens.

Benjamin
- This might be less of a UI thing, but are we only doing an email notification master switch or is it per calendar?
- Really like the preview event, maybe we can implement it as a preview button instead? I feel like it might be confusing otherwise.
- I think it would be interesting to add "every X days/weeks" so that people are not too limited (maybe only ELEC labs every other week for example)

BTW guys, we got 50% participation in this thread, that's as much as US general election!

**Comment by jaslatendresse** [comment]
@g-harel Thanks for feedback. Those are things I didn't think of. For the horizontal lines, it was just a way to make a clear separation. It could be done another way. For the elements that don't need to be there all the time, are you talking about the menu? I do agree that we should keep it as light as possible...like the pending requests could be elsewhere. 

For yours, I like the calendar weekly view, but i find the scroll down menu a bit unintuitive. Otherwise, pretty neat. 

@RemusCM Tabbed layout could be a bit awkward to use for a calendar. I do like the popup window to add events. 

@NepheriusIsTaken good idea for overlapping event! props for using a ruler :) haha 
Preview feature is neat and would be a good idea to implement.

**Comment by NepheriusIsTaken** [comment]
Comments:

@jaslatendresse I'm a fan of dropdown menus. I would prefer that design to a fixed menu approach so that the calendar view can be maximized if needed. I agree with Gabriel's comment as well about the dangers of side scrolling. On the aesthetically side, I find your calendar very nice so good job with taht!

@RemusCM My problem with your approach is the "tabs". I would prefer it if our app only had one window and a menu instead of many windows navigated through tabs.

@g-harel I think we should use your calendar model as a basis for the project. I would prefer a button to switch between weekly and monthly view like in Jasmine's design so that it is obvious for the user. I would also drop the "forgot your password?" line as it implies we implement another feature to the project. Maybe if we have time. I would add a toggle button in the notification section so that someone can choose to be notified by all calendars in a single click. I would have the account portion on your dropdown menu also handle the email / password modifications. Your design doesn't currently handle overlap. I suggest using the "band overlap" demonstrated in my shitty pdf file to handle this case. Instead of the browse overlapping tile dialog, we could also have a pop up window appear whenever we mouse over an event.

**Comment by jaslatendresse** [comment]
@NepheriusIsTaken I agree with you. All designs have their strengths but I think in terms on functionalities, @g-harel seems to be one to go with. We can take his as a base and bring changes according to what other designs had his didn't.

**Comment by eCom0327** [comment]
I agree that **@g-harel** 's design seems best as a base. I assume the user for this design is assumed to be the student? How would it be different or similar to what the professor or TA's interface?
